
[package]

name = "texture-packer"
version = "0.0.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]

[lib]

name = "texture_packer"

[dependencies.image]

git = "https://github.com/PistonDevelopers/rust-image"

