
[package]

name = "packer-test"
version = "0.0.0"
authors = ["Coeuvre <coeuvre@gmail.com>"]

[[bin]]

name = "packer-test"

path = "./packer-test.rs"

[dependencies.texture_packer]

path = "../"

[dependencies.image]

git = "https://github.com/PistonDevelopers/image"
